Feat efg41 integracao api cadastro
natanfelipe/EverisFinancialGoal pull request #18
Opened 2021-06-22 13:41 UTC by joseRobertoMoura

2021-06-22 13:45 UTC, andersonmseveris approved these changes

2021-06-22 17:12 UTC, natanfelipe requested changes
Bom trabalho @joseRobertoMoura ! 🎉 

Comentei alguns pontos para correção e deixar o código ainda melhor. 🔧

2021-06-22 17:12 UTC, natanfelipe commented on app/src/main/java/com/br/everis/financialgoal/data/datasource/worker/cadastro/ImpCadastroDataSource.kt
> +                            message = "Cadastro Realizado com sucesso",
Essa mensagem foi especificada em algum lugar? O backend no retorno tem uma mensagem específica de sucesso e de erro que deveria ser utilizada.

2021-06-22 17:12 UTC, natanfelipe commented on app/src/main/java/com/br/everis/financialgoal/ui/cadastro/fragment/SenhaFragment.kt
> +                    activity?.finish()
Ao invés do `activity?` poderia ser utilizado o `requireActivity`

2021-06-22 17:12 UTC, natanfelipe commented on app/src/main/java/com/br/everis/financialgoal/ui/cadastro/fragment/SenhaFragment.kt
> +                    Toast.makeText(context, it.message, Toast.LENGTH_SHORT).show()
Talvez seria mais interessante ter uma classe utilitária com um método para exibir os Toasts.

2021-06-22 17:12 UTC, natanfelipe commented on app/src/main/java/com/br/everis/financialgoal/viewmodel/cadastro/CadastroViewModel.kt
>      fun init(cadastro: CadastroModelRequest){
Acho que seria melhor mudar o nome da função de `init` para `initializer` pois, já existe uma função padrão chamada `init`.

2021-06-22 17:12 UTC, natanfelipe commented on app/src/main/java/com/br/everis/financialgoal/viewmodel/cadastro/CadastroViewModel.kt
> +    var _response = MutableLiveData<CadastroModelResponse>()
Esse `var` poderia ser `private`

2021-06-22 17:12 UTC, natanfelipe commented on app/src/main/java/com/br/everis/financialgoal/ui/cadastro/fragment/EmailFragment.kt
> +                val cadastroObjectEmail= CadastroModelRequest(edtEmail.text.toString(),"","")
Entendi o motivo de estar passando strings vazias mas, que tal considerar passar elas como `nullable` ou até mesmo já deixa o valor de uma string vazia lá no model e validar lá no final se os valores estão nulos/vazios ou não?

2021-06-22 17:12 UTC, natanfelipe commented on app/src/main/java/com/br/everis/financialgoal/data/datasource/worker/cadastro/ImpCadastroDataSource.kt
> +            withContext(Dispatchers.IO){
Acho q a forma como foi criada essa `coroutines` poderia ser diferente. Que tal, definir o `coroutineScope` como `IO` ao invés de `Main` e executar tudo dentro do `launch`, ao invés de usar o `withContext`?

2021-06-22 17:12 UTC, natanfelipe commented on app/src/main/java/com/br/everis/financialgoal/ui/cadastro/fragment/NomeFragment.kt
>              parentFragmentManager.beginTransaction().apply {
Seria interessante abstrair essa transação de fragments para um método numa classe utilitária para deixar o código com uma maior facilidade de manutenção.

2021-06-22 19:17 UTC, joseRobertoMoura commented on app/src/main/java/com/br/everis/financialgoal/ui/cadastro/fragment/SenhaFragment.kt
> +                    activity?.finish()
feito

2021-06-22 19:17 UTC, joseRobertoMoura commented on app/src/main/java/com/br/everis/financialgoal/viewmodel/cadastro/CadastroViewModel.kt
>      fun init(cadastro: CadastroModelRequest){
feito

2021-06-22 19:17 UTC, joseRobertoMoura commented on app/src/main/java/com/br/everis/financialgoal/viewmodel/cadastro/CadastroViewModel.kt
> +    var _response = MutableLiveData<CadastroModelResponse>()
feito

2021-06-22 19:18 UTC, joseRobertoMoura commented on app/src/main/java/com/br/everis/financialgoal/ui/cadastro/fragment/EmailFragment.kt
> +                val cadastroObjectEmail= CadastroModelRequest(edtEmail.text.toString(),"","")
Essa demanda de verificar se é null, o Anderson está implementando.

2021-06-22 19:18 UTC, joseRobertoMoura commented on app/src/main/java/com/br/everis/financialgoal/data/datasource/worker/cadastro/ImpCadastroDataSource.kt
> +            withContext(Dispatchers.IO){
feito

2021-06-22 19:25 UTC, joseRobertoMoura commented on app/src/main/java/com/br/everis/financialgoal/ui/cadastro/fragment/SenhaFragment.kt
> +                    Toast.makeText(context, it.message, Toast.LENGTH_SHORT).show()
feito

2021-06-22 19:50 UTC, joseRobertoMoura commented on app/src/main/java/com/br/everis/financialgoal/ui/cadastro/fragment/NomeFragment.kt
>              parentFragmentManager.beginTransaction().apply {
feito

2021-06-23 12:28 UTC, natanfelipe requested changes

2021-06-23 12:28 UTC, natanfelipe commented on app/src/main/java/com/br/everis/financialgoal/ui/cadastro/fragment/EmailFragment.kt
> +            navigationFragment(contextActivity,"nome",CadastroModelRequest(edtEmail.text.toString(),null,null))
como os atributos do CadastroModelRequest são nulos, você pode informar só um parametro, da seguinte forma:
`CadastroModelRequest(username = edtEmail.text.toString())`

2021-06-23 12:28 UTC, natanfelipe commented on app/src/main/java/com/br/everis/financialgoal/utils/cadastro/ChangeFragment.kt
> +                context.supportFragmentManager.beginTransaction().apply {
Seria mais interessante criar uma variável e a depender do nome do fragment, você informar qual o fragment que será chamado e fora do when fazer o `beginTransaction` passando o fragment desejado.

2021-06-23 12:28 UTC, natanfelipe commented on app/src/main/java/com/br/everis/financialgoal/utils/cadastro/ChangeFragment.kt
> +                    replace(R.id.fragment, SenhaFragment.newInstance(cadastroObject!!,context))
Procure não usar o `!!` no código. Sempre verifique antes se o objeto é nulo.

2021-06-23 12:34 UTC, joseRobertoMoura commented on app/src/main/java/com/br/everis/financialgoal/ui/cadastro/fragment/EmailFragment.kt
> +            navigationFragment(contextActivity,"nome",CadastroModelRequest(edtEmail.text.toString(),null,null))
feito

2021-06-23 12:45 UTC, joseRobertoMoura commented on app/src/main/java/com/br/everis/financialgoal/utils/cadastro/ChangeFragment.kt
> +                context.supportFragmentManager.beginTransaction().apply {
feito

2021-06-23 12:49 UTC, joseRobertoMoura commented on app/src/main/java/com/br/everis/financialgoal/utils/cadastro/ChangeFragment.kt
> +                    replace(R.id.fragment, SenhaFragment.newInstance(cadastroObject!!,context))
feito

2021-06-23 13:47 UTC, natanfelipe requested changes

2021-06-23 13:47 UTC, natanfelipe commented on app/src/main/java/com/br/everis/financialgoal/ui/cadastro/fragment/SenhaFragment.kt
> +                }else if(!it.res){
Eu reparei agora nesse `else if` que na verdade deveria ser apenas um `else`

2021-06-23 13:52 UTC, natanfelipe approved these changes

2021-06-23 13:53 UTC, merged