Feat efg 66 email dialogup error response
natanfelipe/EverisFinancialGoal pull request #19
Opened 2021-06-22 13:57 UTC by andersonms92

2021-06-22 14:14 UTC, joseRobertoMoura requested changes

2021-06-22 14:14 UTC, joseRobertoMoura commented on app/src/main/java/com/br/everis/financialgoal/ui/cadastro/fragment/EmailFragment.kt
> +class EmailFragment : DialogFragment() {
voltar para Fragment

2021-06-22 14:14 UTC, joseRobertoMoura commented on app/src/main/java/com/br/everis/financialgoal/ui/cadastro/fragment/SenhaFragment.kt
> -           startActivity(Intent(activity,LoggedOutActivity::class.java))
Voltar o startActivity para o if

2021-06-22 16:14 UTC, joseRobertoMoura approved these changes

2021-06-22 17:23 UTC, natanfelipe requested changes
Bom trabalho @andersonms92 🎉 
Fiz alguns comentários para deixar o código ainda melhor. 🔧

2021-06-22 17:23 UTC, natanfelipe commented on app/src/main/java/com/br/everis/financialgoal/ui/cadastro/fragment/EmailFragment.kt
> +            if(fieldValidator.isValidEmail(edtEmail.text.toString())){
Seria interessante extrair essa validação dos campos para uma função

2021-06-22 17:23 UTC, natanfelipe commented on app/src/main/java/com/br/everis/financialgoal/ui/cadastro/fragment/EmailFragment.kt
>              activity?.finish()
Ao invés de utilizar o `activity?` , você pode utilizar o `requireActivity()`

2021-06-22 17:23 UTC, natanfelipe commented on app/src/main/java/com/br/everis/financialgoal/utils/DialogEventManager.kt
> +                TITLE = "E-mail inválido"
Os textos deveriam estar num arquivo de strings.

2021-06-22 17:23 UTC, natanfelipe commented on app/src/main/java/com/br/everis/financialgoal/utils/DialogAlert.kt
> +    fun onAlertDialog(view: View, event: Int) {
Acho que seria interessante passar o título e a mensagem com argumentos da função. Ao invés de ter uma outra classe para controlar os textos.

2021-06-22 17:23 UTC, natanfelipe commented on app/src/main/java/com/br/everis/financialgoal/ui/cadastro/fragment/SenhaFragment.kt
>      private val mockCadastro: CadastroModelRequest = CadastroModelRequest(
E se ao invés de ter uma variável, você criasse uma classe que teria os objetos mockados? Daria para aproveitar tanto nessa situação em que o backend não está integrado como nos testes unitários.

2021-06-22 17:53 UTC, andersonms92 commented on app/src/main/java/com/br/everis/financialgoal/ui/cadastro/fragment/SenhaFragment.kt
>      private val mockCadastro: CadastroModelRequest = CadastroModelRequest(
Esses valores mockados foram retirados projeto final do José. Eu só mantive ele para não acabar mexendo no código que ele fez.

2021-06-23 12:41 UTC, natanfelipe requested changes

2021-06-23 12:41 UTC, natanfelipe commented on app/src/main/java/com/br/everis/financialgoal/ui/cadastro/fragment/EmailFragment.kt
> +        const val TITLE = "E-mail inválido"
Seria melhor colocar esse texto "E-mail inválido" assim como as outras constantes no arquivo `strings.xml`.

2021-06-23 12:41 UTC, natanfelipe commented on app/src/main/java/com/br/everis/financialgoal/ui/cadastro/fragment/EmailFragment.kt
> +        const val TEXT = "forneça um endereço de e-mail válido"
Seria melhor colocar esse texto "forneça um endereço de e-mail válido" assim como as outras constantes no arquivo strings.xml.

2021-06-23 12:41 UTC, natanfelipe commented on app/src/main/java/com/br/everis/financialgoal/ui/cadastro/fragment/NomeFragment.kt
> +        const val TITLE = "Nome/Apelido inválido"
Seria melhor colocar esse texto "O nome/apelido deve ter pelo menos 1 carácter" assim como as outras constantes no arquivo strings.xml.

2021-06-23 12:41 UTC, natanfelipe commented on app/src/main/java/com/br/everis/financialgoal/ui/cadastro/fragment/NomeFragment.kt
> +        const val TEXT = "O nome/apelido deve ter pelo menos 1 carácter"
Seria melhor colocar esse texto "O nome/apelido deve ter pelo menos 1 carácter" assim como as outras constantes no arquivo strings.xml.

2021-06-23 12:41 UTC, natanfelipe commented on app/src/main/java/com/br/everis/financialgoal/ui/cadastro/fragment/SenhaFragment.kt
> +        const val TITLE = "Senha inválida"
Seria melhor colocar esse texto "Senha inválida" assim como as outras constantes no arquivo strings.xml.

2021-06-23 12:41 UTC, natanfelipe commented on app/src/main/java/com/br/everis/financialgoal/ui/cadastro/fragment/SenhaFragment.kt
> +        const val TEXT = "a senha deve ter pelo menos 8 dígitos"
Seria melhor colocar esse texto "a senha deve ter pelo menos 8 dígitos" assim como as outras constantes no arquivo strings.xml.

2021-06-23 12:41 UTC, natanfelipe commented on app/src/main/java/com/br/everis/financialgoal/utils/DialogAlert.kt
> +        alertDialog.getButton(AlertDialog.BUTTON_POSITIVE).setTextColor(Color.rgb(123,31,162))
Seria interessante colocar essa cor no arquivo `colors.xml`

2021-06-23 12:41 UTC, natanfelipe commented on app/src/main/res/layout/fragment_forgotten_password.xml
>          android:layout_width="@dimen/width_300_dp"
Não é uma boa prática usar `width` fixo. Que tal usar o `match_constraint`(`0dp`) caso esteja usando o constraint layout e usar `margins`

2021-06-23 12:41 UTC, natanfelipe commented on app/src/main/res/layout/fragment_forgotten_password.xml
>          app:layout_constraintHorizontal_bias="0.375"
Esse bias é realmente necessário?

2021-06-23 12:41 UTC, natanfelipe commented on app/src/main/res/layout/fragment_forgotten_password.xml
>          android:layout_width="@dimen/width_300_dp"
Não é uma boa prática usar `width` fixo. Que tal usar o `match_constraint`(`0dp`) caso esteja usando o constraint layout e usar `margins`

2021-06-23 12:41 UTC, natanfelipe commented on app/src/main/res/layout/fragment_forgotten_password.xml
>          app:layout_constraintVertical_bias="0.0"
Esse bias é realmente necessário?

2021-06-23 12:41 UTC, natanfelipe commented on app/src/main/res/layout/fragment_forgotten_password.xml
>          app:layout_constraintHorizontal_bias="0.942"
Esse bias é realmente necessário?

2021-06-23 13:27 UTC, andersonms92 commented on app/src/main/java/com/br/everis/financialgoal/ui/cadastro/fragment/EmailFragment.kt
> +        const val TITLE = "E-mail inválido"
Feito

2021-06-23 13:27 UTC, andersonms92 commented on app/src/main/java/com/br/everis/financialgoal/ui/cadastro/fragment/EmailFragment.kt
> +        const val TEXT = "forneça um endereço de e-mail válido"
Feito

2021-06-23 13:27 UTC, andersonms92 commented on app/src/main/java/com/br/everis/financialgoal/ui/cadastro/fragment/NomeFragment.kt
> +        const val TITLE = "Nome/Apelido inválido"
Feito

2021-06-23 13:28 UTC, andersonms92 commented on app/src/main/java/com/br/everis/financialgoal/ui/cadastro/fragment/NomeFragment.kt
> +        const val TEXT = "O nome/apelido deve ter pelo menos 1 carácter"
Feito

2021-06-23 13:28 UTC, andersonms92 commented on app/src/main/java/com/br/everis/financialgoal/ui/cadastro/fragment/SenhaFragment.kt
> +        const val TITLE = "Senha inválida"
Feito

2021-06-23 13:28 UTC, andersonms92 commented on app/src/main/java/com/br/everis/financialgoal/ui/cadastro/fragment/SenhaFragment.kt
> +        const val TEXT = "a senha deve ter pelo menos 8 dígitos"
Feito

2021-06-23 13:35 UTC, andersonms92 commented on app/src/main/java/com/br/everis/financialgoal/utils/DialogAlert.kt
> +        alertDialog.getButton(AlertDialog.BUTTON_POSITIVE).setTextColor(Color.rgb(123,31,162))
Feito

2021-06-23 13:36 UTC, andersonms92 commented on app/src/main/res/layout/fragment_forgotten_password.xml
>          app:layout_constraintHorizontal_bias="0.375"
Removido

2021-06-23 13:38 UTC, andersonms92 commented on app/src/main/res/layout/fragment_forgotten_password.xml
>          app:layout_constraintVertical_bias="0.0"
Não consegui deixar o layout alinhado após retirar esse bias. Então resolvi deixá-lo

2021-06-23 13:39 UTC, andersonms92 commented on app/src/main/res/layout/fragment_forgotten_password.xml
>          app:layout_constraintHorizontal_bias="0.942"
Não consegui deixar o layout alinhado sem o bias 0.942 e o bias 0.0, por isso resolvi deixá-los

2021-06-23 13:41 UTC, andersonms92 commented on app/src/main/res/layout/fragment_forgotten_password.xml
>          android:layout_width="@dimen/width_300_dp"
Feito

2021-06-23 13:41 UTC, andersonms92 commented on app/src/main/res/layout/fragment_forgotten_password.xml
>          android:layout_width="@dimen/width_300_dp"
Feito

2021-06-23 19:10 UTC, natanfelipe requested changes

2021-06-23 19:10 UTC, natanfelipe commented on app/src/main/java/com/br/everis/financialgoal/utils/DialogAlert.kt
> +            .setTextColor(Color.parseColor(
Esse Color.parseColor poderia ficar em um método de uma classe util.

2021-06-23 19:10 UTC, natanfelipe commented on app/src/main/java/com/br/everis/financialgoal/utils/DialogAlert.kt
> +                "#"+Integer.toHexString(
Não precisa desse sinal de + para concatenar.

2021-06-23 19:10 UTC, natanfelipe commented on app/src/main/java/com/br/everis/financialgoal/ui/cadastro/fragment/SenhaFragment.kt
> +    private lateinit var TITLE: String
Como não é uma constante, o ideal é que esse nome não seja em caixa alta.

2021-06-23 19:10 UTC, natanfelipe commented on app/src/main/java/com/br/everis/financialgoal/ui/cadastro/fragment/SenhaFragment.kt
> +    private lateinit var TEXT: String
Como não é uma constante, o ideal é que esse nome não seja em caixa alta.

2021-06-23 19:10 UTC, natanfelipe commented on app/src/main/java/com/br/everis/financialgoal/ui/cadastro/fragment/SenhaFragment.kt
> +    private lateinit var POSITIVE_BUTTON: String
Como não é uma constante, o ideal é que esse nome não seja em caixa alta.

2021-06-23 19:10 UTC, natanfelipe commented on app/src/main/java/com/br/everis/financialgoal/ui/cadastro/fragment/NomeFragment.kt
> +    private lateinit var TITLE: String
Como não é uma constante, o ideal é que esse nome não seja em caixa alta.

2021-06-23 19:10 UTC, natanfelipe commented on app/src/main/java/com/br/everis/financialgoal/ui/cadastro/fragment/NomeFragment.kt
> +    private lateinit var TEXT: String
Como não é uma constante, o ideal é que esse nome não seja em caixa alta.

2021-06-23 19:10 UTC, natanfelipe commented on app/src/main/java/com/br/everis/financialgoal/ui/cadastro/fragment/NomeFragment.kt
> +    private lateinit var POSITIVE_BUTTON: String
Como não é uma constante, o ideal é que esse nome não seja em caixa alta.

2021-06-23 19:10 UTC, natanfelipe commented on app/src/main/java/com/br/everis/financialgoal/ui/cadastro/fragment/EmailFragment.kt
> +    private lateinit var TITLE: String
Como não é uma constante, o ideal é que esse nome não seja em caixa alta.

2021-06-23 19:10 UTC, natanfelipe commented on app/src/main/java/com/br/everis/financialgoal/ui/cadastro/fragment/EmailFragment.kt
> +    private lateinit var TEXT: String
Como não é uma constante, o ideal é que esse nome não seja em caixa alta.

2021-06-23 19:10 UTC, natanfelipe commented on app/src/main/java/com/br/everis/financialgoal/ui/cadastro/fragment/EmailFragment.kt
> +    private lateinit var POSITIVE_BUTTON: String
Como não é uma constante, o ideal é que esse nome não seja em caixa alta.

2021-06-23 23:00 UTC, andersonms92 commented on app/src/main/java/com/br/everis/financialgoal/utils/DialogAlert.kt
> +            .setTextColor(Color.parseColor(
Feito

2021-06-23 23:01 UTC, andersonms92 commented on app/src/main/java/com/br/everis/financialgoal/utils/DialogAlert.kt
> +                "#"+Integer.toHexString(
Não consegui alterar essa concatenação sem que ocorresse algum erro, então deixei assim.

2021-06-23 23:03 UTC, andersonms92 commented on app/src/main/java/com/br/everis/financialgoal/ui/cadastro/fragment/SenhaFragment.kt
> +    private lateinit var TITLE: String
Feito

2021-06-23 23:03 UTC, andersonms92 commented on app/src/main/java/com/br/everis/financialgoal/ui/cadastro/fragment/SenhaFragment.kt
> +    private lateinit var TEXT: String
Feito

2021-06-23 23:03 UTC, andersonms92 commented on app/src/main/java/com/br/everis/financialgoal/ui/cadastro/fragment/EmailFragment.kt
> +    private lateinit var POSITIVE_BUTTON: String
Feito pra todas as variáveis com caixa alta.

2021-06-24 16:33 UTC, natanfelipe requested changes

2021-06-24 16:33 UTC, natanfelipe commented on app/src/main/java/com/br/everis/financialgoal/ui/login/fragment/ForgottenPasswordAlertDialog.kt
> +    private lateinit var positive_button: String
É bom usar o padrão camelCase `positiveButton`

2021-06-24 16:33 UTC, natanfelipe commented on app/src/main/java/com/br/everis/financialgoal/ui/login/fragment/ForgottenPasswordAlertDialog.kt
> +                dialog?.cancel()
Como a classe herda de dialogFragment, pode usar apenas um `dismiss()`

2021-06-24 16:33 UTC, natanfelipe commented on app/src/main/java/com/br/everis/financialgoal/ui/login/fragment/ForgottenPasswordAlertDialog.kt
> +            dialog?.cancel()
Como a classe herda de dialogFragment, pode usar apenas um `dismiss()`

2021-06-24 16:33 UTC, natanfelipe commented on app/src/main/java/com/br/everis/financialgoal/ui/login/fragment/ForgottenPasswordAlertDialog.kt
> +
Essa linha em branco pode ser deletada.

2021-06-24 16:52 UTC, natanfelipe approved these changes

2021-06-24 16:53 UTC, merged