Feat efg 65 integracao api login
natanfelipe/EverisFinancialGoal pull request #22
Opened 2021-06-24 19:00 UTC by agathaappb

2021-06-24 19:17 UTC, andersonms92 approved these changes

2021-06-24 19:51 UTC, natanfelipe requested changes
Bom trabalho @agathaappb ! 🎉 

Tem alguns ajustes que precisam ser feitos para o código ficar ainda melhor. 🔧

2021-06-24 19:51 UTC, natanfelipe commented on app/src/main/java/com/br/everis/financialgoal/ui/login/LoginActivity.kt
> +    fun login(){
Seria uma boa usar um outro nome pra essa função tipo, initViews()

2021-06-24 19:51 UTC, natanfelipe commented on app/src/main/java/com/br/everis/financialgoal/ui/login/LoginActivity.kt
> +        if (fieldValidator.isValidEmail(email.text.toString()) == true){
Acho que o ideal seria fazer essas verificações lá no `viewmodel` e retornar o valor em um `livedata`. Outro ponto é que o `== true` não é necessário.

2021-06-24 19:51 UTC, natanfelipe commented on app/src/main/java/com/br/everis/financialgoal/ui/login/LoginActivity.kt
> +                login()
No clique do botão, deveria ser chamado o método no `viewmodel` responsável por retornar o resultado da requisição e observar o `livedata`.

2021-06-24 19:51 UTC, natanfelipe commented on app/src/main/java/com/br/everis/financialgoal/ui/login/LoginActivity.kt
> +                        Toast.makeText(this,"Deu ruim!",Toast.LENGTH_SHORT).show()
O backend não retorna uma resposta apropriada para ser exibida?

2021-06-24 19:51 UTC, natanfelipe commented on app/src/main/java/com/br/everis/financialgoal/viewmodel/login/LoginViewModel.kt
> +        var resp = MutableLiveData<LoginModelResponse>()
dois pontos nessa linha: 

1. não seria uma boa manter essa variável como privada?
2. mudar o nome dessa variável para algo mais intuitivo tipo loginModelResponse

2021-06-24 19:51 UTC, natanfelipe commented on app/src/main/java/com/br/everis/financialgoal/viewmodel/login/LoginViewModel.kt
> +    fun init(login: LoginModelRequest){
Acho que esse método não tem muita utilidade para esse contexto. Poderia tá chamando o getResponseApi

2021-06-24 19:51 UTC, natanfelipe commented on app/src/main/java/com/br/everis/financialgoal/viewmodel/login/LoginViewModel.kt
> +        val response: LiveData<LoginModelResponse>get() = resp
mudar o nome dessa variável para algo mais intuitivo tipo loginModelResponse

2021-06-24 19:51 UTC, natanfelipe commented on app/src/main/java/com/br/everis/financialgoal/viewmodel/login/LoginViewModel.kt
> +    fun getResponseApi(login:LoginModelRequest){
Acho que seria melhor renomear esse método para algo mais intuitivo tipo `doLogin` e também seria interessante passar o usuário e a senha separados para fazer a validação destes campos no `viewmodel`

2021-06-24 19:51 UTC, natanfelipe commented on app/src/main/res/layout/activity_login.xml
> +        android:id="@+id/frame_laout"
Seria interessante dar um nome mais no padrão tipo `loading_frame_layout` ou `loadingFrameLayout` já que é o padrão seguido no layout.

2021-06-24 19:51 UTC, natanfelipe commented on app/src/main/res/layout/activity_login.xml
> +<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
Fiquei curioso para saber se tem algum motivo para mudar do constraint layout para frame layout. Você poderia explicar a razão dessa mudança?

2021-06-24 19:51 UTC, natanfelipe commented on app/src/main/java/com/br/everis/financialgoal/ui/login/LoginActivity.kt
> +import android.widget.*
Não é uma boa prática utilizar wildcards o `*` no import. Você pode tá pesquisando como desabilita-lo no android studio.

2021-06-24 19:51 UTC, natanfelipe commented on app/src/main/java/com/br/everis/financialgoal/data/datasource/worker/login/ImpLoginDataSource.kt
> +                                message = "Login ok!",
Será que o backend já não retorna uma mensagem de sucesso? Se sim, poderia utiliza-la no lugar da `Login ok!`

2021-06-24 19:51 UTC, natanfelipe commented on app/src/main/AndroidManifest.xml
> +        <activity android:name=".ui.loggedIn.LoggedInActivity"></activity>
Acho que essa activity será portrait também né? Se sim, já é bom deixar configurado pra evitar esquecer.

2021-06-25 01:02 UTC, agathaappb commented on app/src/main/java/com/br/everis/financialgoal/ui/login/LoginActivity.kt
> +                login()
Essa parte inseri dentro de uma função, pois temos as validações dos campos antes de realizar a chamada da viewmodel; com isso ela acabou ficando um pouco mais extensa.

2021-06-25 01:04 UTC, agathaappb commented on app/src/main/java/com/br/everis/financialgoal/ui/login/LoginActivity.kt
> +                login()
neste caso eu mantenho em uma função separada ou passo direto as validações e a chamada da viewmodel?

2021-06-29 12:38 UTC, closed without merging