Bug fix
natanfelipe/EverisFinancialGoal pull request #25
Opened 2021-06-28 14:37 UTC by andersonms92

Ajustes nos DialogUp, Toasts e Imagem

2021-06-28 16:03 UTC, joseRobertoMoura approved these changes

2021-06-28 17:33 UTC, natanfelipe requested changes, later dismissed

2021-06-28 17:33 UTC, natanfelipe commented on app/src/main/java/com/br/everis/financialgoal/ui/cadastro/fragment/SenhaFragment.kt
> +                    edtSenha.text.toString(),
Seria uma boa colocar o valor do edtSenha numa varíavel do tipo `String`

2021-06-28 17:33 UTC, natanfelipe commented on app/src/main/java/com/br/everis/financialgoal/ui/cadastro/fragment/SenhaFragment.kt
> +                cadastroViewModel.response.observe(viewLifecycleOwner) { response ->
Ficou esquisito esse observer aninhado. O ideal seria ter um único observer já que o response code já vai vir na response.

2021-06-28 17:33 UTC, natanfelipe commented on app/src/main/java/com/br/everis/financialgoal/ui/cadastro/fragment/SenhaFragment.kt
> +                            if (it == "200") {
O status code já é verificado no datasource. Aliás, eu achei que o datasource tá bem confuso.

2021-06-28 17:33 UTC, natanfelipe commented on app/src/main/java/com/br/everis/financialgoal/viewmodel/cadastro/CadastroViewModel.kt
> +    private var _responseCode = MutableLiveData<String>()
Não vejo razão em ter esse livedata

2021-06-28 17:33 UTC, natanfelipe commented on app/src/main/java/com/br/everis/financialgoal/data/datasource/worker/cadastro/ImpCadastroDataSource.kt
> +    class RequestSuccess(val success: CadastroModelResponse?, val codeSuccess:String) : CadastroResult()
Não vejo razão em ter esse codeSuccess.

2021-06-28 17:33 UTC, natanfelipe commented on app/src/main/java/com/br/everis/financialgoal/data/datasource/worker/cadastro/ImpCadastroDataSource.kt
> +    class RequestError(val error: CadastroModelResponse?, val codeError:String) : CadastroResult()
Não vejo razão em ter esse codeError. E o outra coisa é que no requestError deveria retornar uma exception

2021-06-28 17:39 UTC, andersonms92 commented on app/src/main/java/com/br/everis/financialgoal/ui/cadastro/fragment/SenhaFragment.kt
> +                    edtSenha.text.toString(),
Feito

2021-06-28 17:56 UTC, andersonms92 commented on app/src/main/java/com/br/everis/financialgoal/data/datasource/worker/cadastro/ImpCadastroDataSource.kt
> +    class RequestError(val error: CadastroModelResponse?, val codeError:String) : CadastroResult()
Essa é uma parte da implementação do Jose.

2021-06-28 17:58 UTC, andersonms92 commented on app/src/main/java/com/br/everis/financialgoal/ui/cadastro/fragment/SenhaFragment.kt
> +                            if (it == "200") {
Parte do código que pertence as modificações do Jose

2021-06-29 12:46 UTC, agathaappb approved these changes
Achei que ficou muito bom as modificações que foram feitas, não tenho nada a acrescentar. ☺

2021-06-29 12:54 UTC, merged